fp_url: "https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/981910/2021-sub-regional-fuel-poverty-tables.xlsx"
parties_models_url: "http://opencouncildata.co.uk/csv1.php"
